AWSTemplateFormatVersion: 2010-09-09
Description: 'Single-instance Portfolio stack'

Parameters:

  Stage:
    Description: Controls the behaviour of the tasks.
    Type: String
    Default: Development
    AllowedValues:
      - Development
      - Production

  ImageTag:
    Description: Docker image tag of the tasks to launch.
    Type: String
    Default: latest
    
Mappings: {}

Metadata: {}

Resources:

  WebPortAddress:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  AssociateWebPort:
    Type: AWS::EC2::EIPAssociation
    Properties:
      AllocationId: !GetAtt WebPortAddress.AllocationId
      NetworkInterfaceId: !Ref webXface

  WebSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VpcId
      GroupDescription: Enable HTTPS access via user defined port
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        FromPort: 443
        IpProtocol: tcp
        ToPort: 443

  webXface:
    Type: AWS::EC2::NetworkInterface
    Properties:
      SubnetId: !Ref SubnetId
      Description: Interface for controlling traffic such as SSH
      GroupSet: 
      - !Ref WebSecurityGroup
      SourceDestCheck: true
      Tags:
        -
          Key: Network
          Value: Web

  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-08f3d892de259504d
      NetworkInterfaces:
        -
          NetworkInterfaceId: !Ref webXface
          DeviceIndex: 0
      Tags:
        -
          Key: Role
          Value: Test Instance
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          yum install ec2-net-utils -y
          ec2ifup eth1
          service httpd start
